### ISSUE TITLE
Multiprovider theme

### ISSUE THREAD

**Issue by sumandas15** [p2-inc/keycloak-themes#11]
I have few question about provider and theme - may be I am asking wrong question due to my limited knowledge

1. Can we be able to support two different providers for authentication - say I want my authentication flow to have 2FA with username and password as 1st step and SMS or Email OTP as 2nd factor ( if Text message is not received, Email OTP as other option)

2. If yes, how theme can be set, I like 'attribute' as login theme. But my SMS provider is different and it has it's own theme. 

3. If no, how this can be solved - any suggestion is valuable. You can correct me and suggest a different approach also.

**Comment by xgp** [comment]
1. Yes, you can do that by configuring a custom authentication flow. Take a look at the Keycloak documentation on that https://www.keycloak.org/docs/latest/server_admin/index.html#_authentication-flows
2. Our `Attribute` login theme isn't meant to be used with other custom themes. In order to do that, you'd probably have to pull the custom templates from your provider's theme or theme-resources into a fork of this project.
